# Generated by Django 5.1.3 on 2024-11-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
