# Generated by Django 5.1.3 on 2024-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzApp', '0002_user_reset_token_user_reset_token_expiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='reset_token_expiry',
            new_name='otp_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_token',
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
